language: go
go:
  - 1.20.x
env:
  global:
  - CGO_ENABLED=0
  - GO111MODULE=on
  - FLYWAY_VERSION=9.15.1
before_script:
  - _script/start-pg
gobuild_args: -a -tags netgo -ldflags '-w'
go_import_path: github.com/adevinta/vulcan-tracker
script:
  - go install ./...
  - go test -short -v $(go list ./... | grep -v /vendor/)
after_success:
  - bash -c 'source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/master/docker.sh)'
