language: go
go:
  - 1.19.x
env:
  global:
  - CGO_ENABLED=0
  - GO111MODULE=on
  - FLYWAY_VERSION=9.15.1
gobuild_args: -a -tags netgo -ldflags '-w'
go_import_path: github.com/adevinta/vulcan-tracker
script:
  - go install ./...
  - go test -short -v $(go list ./... | grep -v /vendor/)
