[api]
max_size = 100
default_size = 20
port = $PORT

[log]
level = "$LOG_LEVEL"

[postgresql]
host = "$PG_HOST"
port = "$PG_PORT"
user = "$PG_USER"
pass = "$PG_PASSWORD"
db = "$PG_NAME"
sslmode = "$PG_SSLMODE"

[aws]
server_credentials_key = "$AWSSERVERCREDENTIALS_KEY"
region ="$AWSREGION"
