[api]
max_size = 100
default_size = 20
port = $PORT

[log]
level = "$LOG_LEVEL"

[jira]
url = "$JIRA_URL"
user = "$JIRA_USER"
token = "$JIRA_TOKEN"
vulnerability_issue_type = "$JIRA_VULNERABILITY_ISSUE_TYPE"
project = "$JIRA_PROJECT"

[kafka]
user = "user"
pass = "supersecret"
broker = "localhost:9092"
topic = "findings-v0"