[api]
max_size = 100
default_size = 20
port = $PORT

[log]
level = "$LOG_LEVEL"

[postgresql]
host = "$PG_HOST"
port = "$PG_PORT"
user = "$PG_USER"
pass = "$PG_PASSWORD"
db = "$PG_NAME"
sslmode = "$PG_SSLMODE"

[jira]
url = "$JIRA_URL"
user = "$JIRA_USER"
token = "$JIRA_TOKEN"
vulnerability_issue_type = "$JIRA_VULNERABILITY_ISSUE_TYPE"
project = "$JIRA_PROJECT"
