#!/bin/bash

# Copyright 2023 Adevinta

set -eu

docker run --name postgres -p ${PG_PORT}:5432 -e POSTGRES_HOST_AUTH_METHOD=trust --rm -d postgres:15.2-alpine

sleep 2

while ! docker exec -it postgres pg_isready; do echo "Waiting for postgres" && sleep 2; done;
