#!/bin/bash

# Copyright 2021 Adevinta

set -e 

docker run --name postgres -p 5439:5439 -e POSTGRES_HOST_AUTH_METHOD=trust -e PGPORT=5439 --rm -d postgres:15.2-alpine

sleep 2

while ! docker exec -it postgres pg_isready; do echo "Waiting for postgres" && sleep 2; done;
