[api]
max_size = 100
default_size = 20
port = 8080

[log]
level = "DEBUG"

[postgresql]
host = "localhost"
port = "5439"
user = "vultrackerdb"
pass = "vultrackerdb"
db = "vultrackerdb"


[servers]
[servers.example1_id]
name = "example1"
url = "http://localhost:8080"
user = "jira_user"
token = "jira_token"
kind = "jira"

[projects]
[projects.example_project_id]
name = "example_project"
server_id = "example1ID"
team_id = "1234-123214-12412-123421"
vulnerability_issue_type = "Vulnerability"
project = "TEST"
fix_workflow = ["ToDo", "In Progress", "Under Review", "Fixed"]
wontfix_workflow = ["Won't Fix"]
