[api]
max_size = 100
default_size = 20
port = 8080

[log]
level = "DEBUG"

[postgresql]
host = "localhost"
port = "5439"
user = "vultrackerdb"
pass = "vultrackerdb"
db = "vultrackerdb"

[aws]
server_credentials_key = "/vulcan/k8s/tracker/jira/"
region ="eu-west-1"
